In [1]:

import warnings

import pandas as pd

# from sklearn.preprocessing import MinMaxScaler

warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv("traffic_data.tar.gz", compression="gzip")

In [6]:
df

       Count
0  102180672

In [4]:
path = r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\\"
# path = r"C:\Users\samcl\Massachusetts Institute of Technology\Truck Parking Capstone - Truck Stop Finder 🚚⛽\\"

In [5]:
df = pd.read_csv("ZIP5_agg_data.csv")

In [6]:
df

,State_1,ZIP5,travel_dir,day_of_week,hours,avg(traffic_volume),median(traffic_volume),stddev(traffic_volume),CV
0,IL,61074,7,2,hour_13,86.173913,81.0,24.200371,0.280832
1,IL,61441,3,7,hour_13,52.936170,49.0,19.121356,0.361215
2,IL,62040,7,2,hour_15,1586.047619,1594.0,76.277719,0.048093
3,IL,61265,3,7,hour_16,922.272727,994.0,183.233163,0.198676
4,IL,62951,5,1,hour_16,1252.560000,1228.0,180.251926,0.143907
...,...,...,...,...,...,...,...,...,...
1921099,TX,78578,7,7,hour_05,48.000000,48.0,NaN,NaN
1921100,TX,77701,3,2,hour_17,3425.500000,3425.5,184.554870,0.053877
1921101,MI,48165,7,3,hour_22,663.000000,663.0,NaN,NaN
1921102,DE,19951,7,6,hour_20,256.000000,256.0,NaN,NaN
1921103,FL,33172,7,7,hour_16,4782.000000,4782.0,NaN,NaN