In [1]:
import pandas as pd
import numpy as np
from haversine import haversine_vector, Unit

In [2]:
df_truck_path = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\5. Source & Refrence Files\0. TruckerPath Data\MIT_2025_High_Volume_Routes_POI_Data - Copy.csv")
df_merged_file = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\4. Working Data Files\Traffic Files\Capstone_truck\merged_filtered_file_11_14.csv")

C:\Users\bhavy\AppData\Local\Temp\ipykernel_20764\2130379377.py:2: DtypeWarning: Columns (2,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df_merged_file = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\4. Working Data Files\Traffic Files\Capstone_truck\merged_filtered_file_11_14.csv")

In [3]:
park_data_1 = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\5. Source & Refrence Files\0. TruckerPath Data\MIT_2025_High_Volume_Routes_Parking_Data_1 - Copy.csv")
park_data_2 = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\5. Source & Refrence Files\0. TruckerPath Data\MIT_2025_High_Volume_Routes_Parking_Data_2 - Copy.csv")
park_data_3 = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\5. Source & Refrence Files\0. TruckerPath Data\MIT_2025_High_Volume_Routes_Parking_Data_3 - Copy.csv")
park_data = pd.concat([park_data_1, park_data_2, park_data_3], ignore_index=True)

In [4]:
df_truck_path.head(2)

,truckParkingSpotCount,showerCount,location,overnightParking,address,Pin ID,phone,state,laundry,lat,lng
0,312.0,9.0,"[-86.87248630306287, 34.050601881119654]",True,426 AL-69,c81e728d9d4c2f636f067f89cc14862c,12562871299,AL,True,34.050602,-86.872486
1,50.0,6.0,"[-85.95542833862305, 32.405957794002745]",True,428 Main St,a87ff679a2f3e71d9181a67b7542122c,1(334)727-3354,AL,True,32.405958,-85.955428

In [5]:
df_merged_file.columns

Index(['datayear', 'stateid', 'routeid', 'beginpoint', 'endpoint', 'f_system',
       'facility_type', 'urban_id', 'through_lanes', 'aadt', 'aadt_date',
       'is_restricted', 'nhs', 'county_id', 'ownership',
       'maintenance_operations', 'managed_lanes', 'managed_lanes_type',
       'peak_lanes', 'counter_peak_lanes', 'toll_id', 'lane_width',
       'median_type', 'median_width', 'shoulder_type', 'shoulder_width_r',
       'shouder_width_l', 'peak_parking', 'dir_through_lanes', 'turn_lanes_r',
       'turn_lanes_l', 'signal_type', 'pct_green_time', 'number_signals',
       'stop_signs', 'at_grade_other', 'aadt_single_unit', 'aadt_combination',
       'pct_dh_single_unit', 'pct_dh_combination', 'k_factor', 'dir_factor',
       'future_aadt', 'future_aadt_year', 'access_control', 'speed_limit',
       'iri', 'iri_date', 'psr', 'surface_type', 'rutting', 'faulting',
       'cracking_percent', 'year_last_improvement', 'year_last_construction',
       'last_overlay_thickness', 'thickness_rigid', 'thickness_flexible',
       'base_type', 'base_thickness', 'soil_type', 'widening_potential',
       'widening_obsticles', 'curves_a', 'curves_b', 'curves_c', 'curves_d',
       'curves_e', 'curves_f', 'terrain_type', 'grades_a', 'grades_b',
       'grades_c', 'grades_d', 'grades_e', 'grades_f', 'pct_pass_sight',
       'travel_time_code', 'route_qualifier', 'route_signing', 'route_number',
       'structure_type', 'is_sample', 'strahnet', 'nn', 'nhfn',
       'shoulder_width_l', 'sample_id', 'key', 'Shape_Length', 'LINE_BEARING',
       'START_LAT', 'START_LONG', 'END_LAT', 'END_LONG', 'DIST', 'MID_LAT',
       'MID_LONG'],
      dtype='object')

In [6]:
df_truck_path = df_truck_path[["Pin ID", "lat", "lng", "truckParkingSpotCount"]].drop_duplicates()
df_merged_file = df_merged_file[["routeid", "beginpoint", "endpoint", "f_system", "MID_LAT",
       "MID_LONG"]].drop_duplicates()

In [7]:
df_merged_file = df_merged_file[~df_merged_file["MID_LAT"].isnull()].copy()

In [8]:
df_stop = pd.merge(df_truck_path, df_merged_file, how="cross")

In [9]:
df_stop['distance_miles'] = haversine_vector(df_stop[['lat', 'lng']],
    df_stop[['MID_LAT', 'MID_LONG']],
    Unit.MILES
)*1.16

In [10]:
df_stop

,Pin ID,lat,lng,truckParkingSpotCount,routeid,beginpoint,endpoint,f_system,MID_LAT,MID_LONG,distance_miles
0,c81e728d9d4c2f636f067f89cc14862c,34.050602,-86.872486,312.0,AL0000120000,21.789,21.810,3,31.751882,-88.114977,202.317830
1,c81e728d9d4c2f636f067f89cc14862c,34.050602,-86.872486,312.0,IN0005650000,11.979,12.026,1,34.689744,-86.716074,52.260786
2,c81e728d9d4c2f636f067f89cc14862c,34.050602,-86.872486,312.0,AL0000120000,127.826,127.828,3,31.346290,-86.525873,218.002763
3,c81e728d9d4c2f636f067f89cc14862c,34.050602,-86.872486,312.0,AL0000121000,186.625,189.521,3,31.302009,-85.767341,232.564612
4,c81e728d9d4c2f636f067f89cc14862c,34.050602,-86.872486,312.0,IN0000100000,21.866,21.930,1,30.637412,-88.094546,285.795314
...,...,...,...,...,...,...,...,...,...,...,...
236604519,fdc899369c3511966cedb8473e1782fb,32.424707,-81.791215,10.0,92471000,37.100,37.186,2,28.300524,-81.358629,331.896313
236604520,fdc899369c3511966cedb8473e1782fb,32.424707,-81.791215,10.0,90020000,9.959,9.965,3,24.625492,-81.598969,625.240470
236604521,fdc899369c3511966cedb8473e1782fb,32.424707,-81.791215,10.0,16060000,9.400,9.500,3,28.015258,-81.915309,353.514517
236604522,fdc899369c3511966cedb8473e1782fb,32.424707,-81.791215,10.0,10075000,28.800,28.900,1,28.025302,-82.338011,354.630609
236604523,fdc899369c3511966cedb8473e1782fb,32.424707,-81.791215,10.0,72280000,0.500,0.600,1,30.110515,-81.509969,186.476474

In [11]:
idx = df_stop.groupby('Pin ID')['distance_miles'].idxmin()
nearest = df_stop.loc[idx].reset_index()

In [12]:
nearest = nearest[["Pin ID", "lat", "lng", "truckParkingSpotCount", "f_system", "routeid", "beginpoint", "endpoint"]].copy()

In [13]:
nearest

,Pin ID,lat,lng,truckParkingSpotCount,f_system,routeid,beginpoint,endpoint
0,00038787e666dbf59f419128a0ee3a66,30.406303,-81.743304,97.0,3,72080000,7.600,7.700
1,0007cda84fafdcf42f96c4f4adb7f8ce,28.529926,-81.731362,0.0,3,11200000,13.400,13.500
2,005b00cc243fb4f39296fa0f16a21482,30.612343,-86.978559,50.0,1,58002000,13.700,13.800
3,0064203b17d778528816f80ef1e29208,30.766060,-85.686060,NaN,1,52002000,17.100,17.129
4,00c23232a9ac7754e1c515d4b6a63f2e,28.799962,-81.274442,0.0,3,77010000,12.500,12.600
...,...,...,...,...,...,...,...,...
1607,fecf8417ed709b82623dde69c75c46bc,34.716627,-87.688432,NaN,3,AL0000020000,24.898,24.931
1608,fee03b7e1be695f06ffdc8203f79e52a,33.878155,-84.734239,NaN,1,1000100040200INC,39.376,39.476
1609,ff1ced3097ccf17c1e67506cdad9ac95,32.379220,-82.061574,20.0,1,1000100040400INC,103.446,103.546
1610,ff39ad2009df462df3dc2ec010c1add8,26.147443,-80.629998,NaN,1,86075000,29.700,29.800
1611,ff54a86f51cf791a850133ddc157b364,30.324783,-81.765593,10.0,1,72001000,21.400,21.426

In [14]:
stop_name_df = park_data[["pinname", "pin id"]].drop_duplicates()
stop_name_df

,pinname,pin id
0,Rest Area WB,005b00cc243fb4f39296fa0f16a21482
512,Friendly Express #31,f312db0543cc671be332446ebb76d2e9
633,Rest Area EB,41dbaeec4466f58cd76a81b7add4a279
1621,Rest Area WB,98c2473648afc991669f9b9334c11072
1652,Spartanburg Walmart Supercenter Store #1035,0bc10d8a74dbafbf242e30433e83aa56
...,...,...
1759820,ONE9 Dealer (One9 Fuel Network) #1365,928e734545f99a375312f4a20606f560
1760145,McDonald's,d3fdb21345d8171619904e061ad625c2
1760229,Marathon #102,665d5cbb82b5785d9f344c46417c6c36
1761273,"Truck Parking Club - Crawfordville, FL Truck a...",95d44ae4e547e2d248598628cb571fc8
1761274,Dollar General,29f6037b034c376b03078fa6d5a4417a

In [15]:
stop_tab_df = pd.merge(nearest, stop_name_df, left_on="Pin ID", right_on="pin id", how="left")

In [16]:
stop_tab_df["link_id"] = stop_tab_df["routeid"].astype("str") + "_" + stop_tab_df["beginpoint"].astype("str") + "_" + stop_tab_df["endpoint"].astype("str")
stop_tab_df = stop_tab_df[["pin id", "pinname", "lat", "lng", "truckParkingSpotCount", "f_system", "link_id"]].copy()
stop_tab_df["review_score"] = ""
stop_tab_df["amenities_score"] = ""
stop_tab_df

,pin id,pinname,lat,lng,truckParkingSpotCount,f_system,link_id,review_score,amenities_score
0,00038787e666dbf59f419128a0ee3a66,Truck Spot Properties,30.406303,-81.743304,97.0,3,72080000_7.6_7.7,,
1,0007cda84fafdcf42f96c4f4adb7f8ce,Clermont Walmart Supercenter Store #2695,28.529926,-81.731362,0.0,3,11200000_13.4_13.5,,
2,005b00cc243fb4f39296fa0f16a21482,Rest Area WB,30.612343,-86.978559,50.0,1,58002000_13.7_13.8,,
3,0064203b17d778528816f80ef1e29208,"Truck Parking Club - Bonifay, FL Truck & Trail...",30.766060,-85.686060,NaN,1,52002000_17.1_17.129,,
4,00c23232a9ac7754e1c515d4b6a63f2e,SFG Farmers Market,28.799962,-81.274442,0.0,3,77010000_12.5_12.6,,
...,...,...,...,...,...,...,...,...,...
1607,fecf8417ed709b82623dde69c75c46bc,Tuscumbia Texaco,34.716627,-87.688432,NaN,3,AL0000020000_24.898_24.931,,
1608,fee03b7e1be695f06ffdc8203f79e52a,Affordable Parking,33.878155,-84.734239,NaN,1,1000100040200INC_39.376_39.476,,
1609,ff1ced3097ccf17c1e67506cdad9ac95,bp,32.379220,-82.061574,20.0,1,1000100040400INC_103.446_103.546,,
1610,ff39ad2009df462df3dc2ec010c1add8,Rest area,26.147443,-80.629998,NaN,1,86075000_29.7_29.8,,
1611,ff54a86f51cf791a850133ddc157b364,Alpha Truck Center,30.324783,-81.765593,10.0,1,72001000_21.4_21.426,,

# Ginny & Christina data check

In [56]:
df_comb = pd.read_csv(r"C:\Users\bhavy\Massachusetts Institute of Technology\Truck Parking Capstone - General\Truck Stop Finder 🚚⛽\4. Working Data Files\TruckStopsCombined.csv")
df_comb = df_comb[["StoreNumber", "Latitude", "Longitude", "ParkingSpaces"]].drop_duplicates()

In [57]:
df_comb = pd.merge(stop_tab_df, df_comb, how="cross")

In [58]:
df_comb['distance_miles'] = haversine_vector(df_comb[['lat', 'lng']],
    df_comb[['Latitude', 'Longitude']],
    Unit.MILES
)*1.16

In [59]:
idx = df_comb.groupby('pin id')['distance_miles'].idxmin()
df_comb_nearest = df_comb.loc[idx].reset_index()

In [60]:
# df_comb_nearest.to_excel("1.xlsx")

In [65]:
gc_tp_df = df_comb_nearest.copy()
# gc_tp_df

In [76]:
gc_tp_df_gp = gc_tp_df.groupby(["StoreNumber"]).agg({"StoreNumber": "count", "Latitude": "count"})
gc_tp_df_gp

             StoreNumber  Latitude
StoreNumber
Love's_307             1         1
Love's_326             1         1
Love's_561             1         1
Love's_765             2         2
Love's_773             1         1
Love's_808             1         1
Love's_818             1         1
Pilot_1390             1         1
Pilot_1403             1         1
Pilot_1415             1         1
Pilot_1436             1         1
Pilot_1550             1         1
Pilot_260              1         1
Pilot_302              1         1
Pilot_310              1         1
Pilot_312              2         2
Pilot_331              1         1
Pilot_352              1         1
Pilot_416              1         1
Pilot_421              2         2
Pilot_422              1         1
Pilot_425              1         1
Pilot_453              1         1
Pilot_4556             1         1
Pilot_60               1         1
Pilot_601              1         1
Pilot_602              1         1
Pilot_603              1         1
Pilot_604              1         1
Pilot_622              1         1
Pilot_625              1         1
Pilot_626              1         1
Pilot_627              1         1
Pilot_628              1         1
Pilot_631              1         1
Pilot_632              1         1
Pilot_66               1         1
Pilot_71               1         1
Pilot_711              1         1
Pilot_713              1         1
Pilot_75               1         1
Pilot_873              1         1
Pilot_91               1         1
Pilot_94               1         1
TA_248                 1         1
TA_268                 1         1
TA_288                 1         1
TA_418                 2         2
TA_425                 1         1
TA_435                 1         1
TA_465                 1         1
TA_477                 1         1
TA_485                 1         1
TA_505                 1         1

In [ ]:
gc_tp_df_gp = gc_tp_df.groupby(["StoreNumber"]).agg({"StoreNumber": "count"}).reset_index()

gc_tp_df = gc_tp_df[gc_tp_df["distance_miles"]<.1].copy()
gc_tp_df = gc_tp_df[(gc_tp_df["truckParkingSpotCount"] != 0)].copy()
gc_tp_df = gc_tp_df[(~gc_tp_df["truckParkingSpotCount"].isnull())].copy()
gc_tp_df = gc_tp_df[gc_tp_df["truckParkingSpotCount"] != gc_tp_df["ParkingSpaces"]].copy()
gc_tp_df

,index,pin id,pinname,lat,lng,truckParkingSpotCount,f_system,link_id,review_score,amenities_score,StoreNumber,Latitude,Longitude,ParkingSpaces,distance_miles
67,116063,0840483dc069597b0629f3bdd5859083,TA Lake City #288,29.994804,-82.596446,180.0,3,29030000_9.8_9.899,,,TA_288,29.995580,-82.596720,250.0,0.065003
86,149187,0bb4aec1710521c12ee76289d9440817,ONE9 Travel Center #453,35.077797,-81.703533,100.0,1,11010008500N_89.56_89.76,,,Pilot_453,35.078273,-81.703917,103.0,0.045721
107,184989,0e139b17a92b2df7d6c3c840e51465fe,Chevron,33.513145,-82.445004,18.0,1,1000100040200INC_175.3026_175.392,,,TA_435,33.513212,-82.445347,69.0,0.023525
191,329584,1b829e73430744463fbf634480db5862,GHANSHYAM FOOD LLC,32.405940,-85.956520,5.0,1,IN0000850000_22.392_22.455,,,TA_505,32.405600,-85.955600,50.0,0.067957
195,337264,1c0ee4bbf575096de4e08ba2e17978ef,Pilot Travel Center #1436,32.471537,-85.690374,20.0,1,IN0000850000_38.991_39.091,,,Pilot_1436,32.471750,-85.690040,93.0,0.028340
234,403870,23363e9a5104d797987048558121b51f,"IdleAir at Newnan, GA",33.320596,-84.778316,51.0,1,1000100040300INC_40.922_41.022,,,Pilot_422,33.321115,-84.777822,95.0,0.053154
311,536888,31f81674a348511b990af268ca3a8391,ONE9 Dealer (One9 Fuel Network) #1415,28.753714,-82.099267,50.0,1,18130000_14.127_14.2,,,Pilot_1415,28.753690,-82.098670,21.0,0.041993
341,587836,3988c7f88ebcb58c6ce932b957b6f332,Pilot Travel Center #94,26.894133,-82.009280,39.0,1,01075000_12.0_12.1,,,Pilot_94,26.894739,-82.009275,44.0,0.048603
343,591587,39b674dd50f7079cd40bd4044a3118d9,Flying J Travel Center #631,30.640991,-83.189762,200.0,1,1000100040100INC_1.4_1.5,,,Pilot_631,30.641236,-83.190486,207.0,0.053650
349,601985,3aa6100288f6904c21d97aa0d6e085af,Flying J Travel Center #711,35.142136,-81.509681,148.0,1,11010008500N_101.99_103.97,,,Pilot_711,35.142827,-81.509162,154.0,0.064987
357,615359,3ce3bd7d63a2c9c81983cc8e9bd02ae5,Pilot Travel Center #71,32.188259,-81.195549,112.0,1,1000100040500INC_107.6_107.7,,,Pilot_71,32.188259,-81.195549,125.0,0.000000
364,627408,3def184ad8f4755ff269862ea77393dd,Pilot Travel Center #75,30.872861,-88.046869,125.0,3,AL0000130000_10.164_10.264,,,Pilot_75,30.872861,-88.046869,77.0,0.000000
391,673744,4251e32f3a849561cb1f7f844257ccef,TA Express Statesboro #418,32.303582,-81.871148,132.0,3,1000100007300INC_26.2334_26.315,,,TA_418,32.303070,-81.872155,125.0,0.079568
394,679161,42a19e8a17c02dfa58c634ac57a1037f,Chevron,33.681554,-85.263703,30.0,1,1000100040200INC_4.5_4.6,,,Pilot_312,33.682548,-85.263639,90.0,0.079799
406,699982,44b422a6d1df1d47db5d50a8d0aaca5d,Flying J Travel Center #601,33.321634,-87.046503,150.0,1,IN0000590000_104.246_104.346,,,Pilot_601,33.321634,-87.046503,163.0,0.000000
415,715630,46922a0880a8f11f8f69cbb52b1396be,$ parking Pilot Dealer,25.884676,-80.365669,62.0,3,87090000_6.8_6.9,,,Pilot_873,25.884676,-80.365669,65.0,0.000000
418,720213,46d0671dd4117ea366031f87f3aa0093,TA Montgomery #425,32.327660,-86.332204,254.0,1,IN0000650000_168.281_168.381,,,TA_425,32.327460,-86.332210,125.0,0.016040
428,737446,4837ba5cd49c7f03caaa423049e66daf,One9 Dealer (One9 Fuel Network) #1331,35.046880,-81.812332,150.0,1,42010008500N_83.132_83.48,,,TA_477,35.046879,-81.812281,80.0,0.003326
431,743030,48e95c45c8217961bf6cd7696d80d238,Flying J Travel Center #625,28.009680,-82.303342,30.0,1,10190000_17.4_17.423,,,Pilot_625,28.010533,-82.303600,40.0,0.070771
443,763688,4b04b0dcd2ade339a3d7ce13252a29d4,Flying J Travel Center #632,34.576440,-84.947150,200.0,1,1000100040100INC_319.726_319.826,,,Pilot_632,34.576835,-84.946624,209.0,0.046983
488,840589,512623b71bfaeea5b53cc62dd60c22f6,"IdleAir at Jackson, GA",33.206553,-84.058820,31.0,1,1000100040100INC_200.817_200.917,,,TA_268,33.206500,-84.058500,108.0,0.021848
496,855261,52b192d69a235b3833acc8f106178f74,Pilot Travel Center #1390,32.182243,-81.456933,25.0,1,1000100040400INC_141.927_142.027,,,Pilot_1390,32.181630,-81.457700,72.0,0.071537
505,870386,543857f4a06c852113bcc02abf295eb5,Flying J Travel Center #627,31.140854,-81.578249,150.0,1,1000100040500INC_29.2433_29.311,,,Pilot_627,31.140854,-81.578249,155.0,0.000000
509,877066,555d6702c950ecb729a966504af0a635,Pilot Travel Center #302,30.559410,-88.205244,65.0,1,IN0000100000_13.169_13.269,,,Pilot_302,30.559410,-88.205244,72.0,0.000000
518,893155,56577889b3c1cd083b6d7b32d32f99d5,Jacks Truck Stop - AMBEST,34.115690,-86.862769,100.0,1,IN0000650000_303.48_303.58,,,Pilot_1550,34.116643,-86.863208,72.0,0.081748
547,942114,59f51fd6937412b7e56ded1ea2470c25,TA Jacksonville South #248,30.066100,-81.496100,137.0,1,78080000_32.074_32.1,,,TA_248,30.066100,-81.496100,87.0,0.000000
581,1000860,5ef059938ba799aaa845e1c2e8a762bd,Pilot Travel Center #66,34.119747,-83.761646,70.0,1,1000100040300INC_129.334_129.434,,,Pilot_66,34.119723,-83.761654,85.0,0.002029
605,1041688,62d360f2a4a2a0f215712e3284ee6112,Hardee’s,32.866306,-87.922269,3.0,1,IN0000590000_40.697_40.724,,,Love's_773,32.866700,-87.922208,96.0,0.031877
622,1071738,66fae5b05c0f64c4d2bdcdf1ad85f7b2,Flying J Travel Center #622,27.449632,-80.398071,156.0,1,94001000_17.863_17.9,,,Pilot_622,27.449632,-80.398071,166.0,0.000000
649,1117762,6aba93256fe216001977444fd1eeac8e,301 Truck Stop,32.302902,-81.873137,15.0,3,1000100007300INC_26.2334_26.315,,,TA_418,32.303070,-81.872155,125.0,0.067909
665,1144981,6cd3e6c48277b430eb30a9290ae77172,Bojangles,31.580471,-84.106639,14.0,3,1000100052000INC_87.528_87.6209,,,Love's_808,31.581169,-84.106279,100.0,0.061112
683,1176598,6f5e931319a4f368c99635364d484749,"IdleAir at Dalton, GA",34.656258,-84.980250,42.0,1,1000100040100INC_325.677_325.777,,,Pilot_421,34.655613,-84.981043,95.0,0.073524
725,1248982,76c538125fc5c9ec6ad1d05650a57de5,Flying J Travel Center #602,33.562587,-86.830746,157.0,1,IN0000650000_263.336_263.398,,,Pilot_602,33.562347,-86.831540,170.0,0.056412
726,1250726,7776e88b0c189539098176589250bcba,Flying J Travel Center #626,29.749927,-81.343694,160.0,1,78080000_8.125_8.2,,,Pilot_626,29.749927,-81.343694,173.0,0.000000
730,1258010,785cf0a5def4977e0210f07e0f925fa1,Pilot Travel Center #4556,28.874241,-82.090056,75.0,1,18130000_22.661_22.7,,,Pilot_4556,28.874241,-82.090056,89.0,0.000000
775,1334748,7f1de29e6da19d22b51c68001e7e0e54,Pilot Travel Center #91,30.065564,-81.493909,30.0,1,78080000_32.05_32.06,,,Pilot_91,30.065564,-81.493909,17.0,0.000000
780,1343333,7f6ffaa6bb0b408017b62254211691b5,Pilot Travel Center #60,33.416913,-80.666755,100.0,1,38010002600E_158.94_160.21,,,Pilot_60,33.417352,-80.666224,48.0,0.049991
787,1355685,8073bd4ed0fe0c330290c58056a2cd5e,Flying J Travel Center #603,31.191715,-85.399355,158.0,3,AL0002100000_13.632_13.732,,,Pilot_603,31.191843,-85.400127,165.0,0.053954
833,1434071,874063a513f432627014a76086be8b17,Chix-n-Wings,33.207656,-84.057317,8.0,1,1000100040100INC_200.917_200.9528,,,Love's_307,33.208091,-84.058520,40.0,0.087894
861,1483432,8c38cb7a6a5df299236cd4a87f70ab98,ONE9 Dealer #1403,30.446144,-82.934268,5.0,1,32100000_9.2_9.3,,,Pilot_1403,30.446124,-82.934263,10.0,0.001606
874,1504630,8df42b4aa26402ac8a3036c3290505a6,LOVES #326 TRAVEL STOP,33.458279,-80.735647,15.0,3,38020030100N_22.2_22.3,,,Love's_326,33.457976,-80.735242,50.0,0.036377
921,1586196,9529fbba677729d3206b3b9073d1e9ca,Pilot Travel Center #421,34.655882,-84.980582,90.0,1,1000100040100INC_325.5771_325.677,,,Pilot_421,34.655613,-84.981043,95.0,0.037290
1005,1730050,a1313bec66a803f38868ce8d864719f6,Godfather's Pizza Express,34.227471,-83.499254,3.0,1,1000100040300INC_146.492_146.5746,,,Love's_765,34.227399,-83.499387,114.0,0.010531
1028,1770285,a4f23670e1833f3fdb077ca70bbd5d66,Pilot Travel Center #331,33.685290,-84.311462,30.0,1,1000100040700INC_50.326_50.3399,,,Pilot_331,33.685437,-84.312174,100.0,0.048938
1054,1815193,a8ef1979aeec2737ae3830ec543ed0df,Flying J Travel Center #604,32.194221,-86.419680,145.0,1,IN0000650000_157.501_157.601,,,Pilot_604,32.194557,-86.420349,160.0,0.052774
1062,1828554,aa3a8fa180b57cc7b71c9359b1555e44,Carolina’s Travel Plaza – Professional Transpo...,34.504781,-82.965251,100.0,1,04010008500N_4.03_4.09,,,TA_465,34.504640,-82.965490,130.0,0.019425
1111,1912476,b32e8760418e68f23c811a1cfd6bda78,AmBest,34.227798,-83.498901,165.0,1,1000100040300INC_146.492_146.5746,,,Love's_765,34.227399,-83.499387,114.0,0.045386
1129,1944094,b5b2e67b2b72a702cd979f99c153c6d0,"IdleAir at Duncan, SC",34.915875,-82.107652,24.0,1,42010008500N_63.27_64.059,,,Pilot_310,34.915732,-82.107788,35.0,0.014546
1146,1973424,b83aac23b9528732c23cc7352950e880,Pilot Travel Center #425,30.485112,-84.420724,90.0,1,50001000_32.2_32.3,,,Pilot_425,30.485112,-84.420724,98.0,0.000000
1221,2102699,c42f891cebbc81aa59f8f183243ac2b9,ONE9 Travel Center (One9 Fuel Network) #713,34.340229,-79.532727,200.0,3,17040003800W_6.0_6.1,,,Pilot_713,34.339724,-79.532875,208.0,0.041632
1244,2141789,c81e728d9d4c2f636f067f89cc14862c,Petro Dodge City #397,34.050602,-86.872486,312.0,1,IN0000650000_298.955_299.055,,,TA_485,34.050780,-86.872340,322.0,0.017268
1263,2174775,caf1a3dfb505ffed0d024130f58c5cfa,Pilot Travel Center #416,31.960264,-83.746610,60.0,1,1000100040100INC_100.5291_100.545,,,Pilot_416,31.960264,-83.746610,67.0,0.000000
1360,2341670,d947bf06a885db0d477d707121934ff8,Pilot Travel Center #352,26.655226,-81.801737,80.0,1,12075000_24.0_24.067,,,Pilot_352,26.655936,-81.802483,92.0,0.078019
1396,2403603,dd1016d687d5960a8f279198a94d0cc5,"Newborn TruckStop, Tallapoosa GA",33.681568,-85.264077,125.0,1,1000100040200INC_4.5_4.6,,,Pilot_312,33.682548,-85.263639,90.0,0.083789
1413,2432314,dff1078356feee05abb8e4f252655765,McDonald's,30.734339,-86.349261,9.0,1,60002000_2.5_2.6,,,Love's_561,30.733881,-86.349145,82.0,0.037560
1440,2478705,e464f78f1b3fa6bfe6d887029bf66f0c,Exxon,33.646157,-85.506025,25.0,1,IN0000200000_204.819_204.919,,,Love's_818,33.647017,-85.506004,72.0,0.068980
1478,2544920,ec0f40c389aeef789ce03eb814facc6c,Flying J Travel Center #628,34.347462,-83.322320,190.0,1,1000100040300INC_159.624_159.724,,,Pilot_628,34.347462,-83.322320,203.0,0.000000
1566,2696134,f8ea2e8463760785106490befc78c339,Pilot Travel Center #260,31.580644,-84.086078,80.0,3,1000100052000INC_88.721_88.821,,,Pilot_260,31.580923,-84.085780,71.0,0.030207

### Intra Chris duplicates

In [42]:
a = df_comb_nearest[['pin id', 'pinname', 'lat', 'lng', 'truckParkingSpotCount']].drop_duplicates()
a = pd.merge(a, a, how="cross")
a['distance_miles'] = haversine_vector(a[['lat_x', 'lng_x']],
    a[['lat_y', 'lng_y']],
    Unit.MILES
)*1.16

In [43]:
a = a[a["distance_miles"]<.1].copy()

In [46]:
a = a[a["pin id_x"] != a["pin id_y"]].copy()
a.dropna(inplace=True)
a = a[a["truckParkingSpotCount_x"] != 0].copy()
a = a[a["truckParkingSpotCount_y"] != 0].copy()
print(a.shape)
a = a[a["truckParkingSpotCount_y"] != a["truckParkingSpotCount_x"]].copy()
print(a.shape)
a['bigger'] = np.where(a["truckParkingSpotCount_y"] > a["truckParkingSpotCount_x"], "y", "x")
a["truckParkingSpotCount_y"] = np.where(a['bigger']=="x", 0, a["truckParkingSpotCount_y"])
a["truckParkingSpotCount_x"] = np.where(a['bigger']=="y", 0, a["truckParkingSpotCount_x"])
a

(80, 12)
(80, 12)

,pin id_x,pinname_x,lat_x,lng_x,truckParkingSpotCount_x,pin id_y,pinname_y,lat_y,lng_y,truckParkingSpotCount_y,distance_miles,bigger
188120,0f7dfe5e8787efa0406adbb556d76c4a,Rest Area NB,31.008825,-85.407196,0.0,b59978537754917c2df87b96ac795ef2,Rest Area SB,31.008808,-85.407251,8.0,0.004034,y
219491,116e195af1954fe5253cf0a55f07ef48,Rest Area SB,26.549514,-81.792156,0.0,2807e5da47a64f8e7f640390a55efc9d,Lee County Rest Area,26.549569,-81.792195,40.0,0.005204,y
219635,116e195af1954fe5253cf0a55f07ef48,Rest Area SB,26.549514,-81.792156,0.0,4490759a6b69ecb7c170d8e1476be569,Lee County Rest Area,26.549272,-81.792249,20.0,0.020531,y
287288,1961aadca386eb5de3a75111cdffcbed,Manatee County Rest Area,27.584565,-82.614143,0.0,3bc188adb791a56ccce03630b0d9f593,Rest Area NB,27.584546,-82.614169,16.0,0.002426,y
308941,1b829e73430744463fbf634480db5862,GHANSHYAM FOOD LLC,32.405940,-85.956520,0.0,a87ff679a2f3e71d9181a67b7542122c,Petro Shorter #348,32.405958,-85.955428,50.0,0.073883,y
...,...,...,...,...,...,...,...,...,...,...,...,...
2470470,f36f265c30f00a3c78eb5fba5c89ee87,Gupta Travel Plaza,33.590028,-86.163331,0.0,8efa9015a4ef4632a954e820eca834ad,I-20 TRUCK STOP,33.589529,-86.163795,100.0,0.050580,y
2470831,f36f265c30f00a3c78eb5fba5c89ee87,Gupta Travel Plaza,33.590028,-86.163331,0.0,c85116ddf63252b9b45f31d7f4938681,The Doghouse Pub & Grill,33.590504,-86.163333,20.0,0.038085,y
2560919,fc95b36228f25a538205290b9fc70438,China Queen,33.529298,-84.661676,0.0,aa5ac3421388b6b3c67f7a545fd46cc9,JP BP - Palmetto,33.528677,-84.662145,8.0,0.058862,y
2561055,fc95b36228f25a538205290b9fc70438,China Queen,33.529298,-84.661676,0.0,c063c0736a23234b286331c4df438050,JP BP - Palmetto 264,33.528594,-84.662293,5.0,0.069956,y
2570657,fd5ac6ce504b74460b93610f39e481f7,Pilot Travel Center #310,34.915732,-82.107788,35.0,b5b2e67b2b72a702cd979f99c153c6d0,"IdleAir at Duncan, SC",34.915875,-82.107652,0.0,0.014546,x

In [35]:
# a.to_excel("Intra Chris comp.xlsx", index=False)

In [50]:
id_x = a[["pin id_x", "truckParkingSpotCount_x"]].drop_duplicates().copy()
id_y = a[["pin id_y", "truckParkingSpotCount_y"]].drop_duplicates().copy()
id_x.rename(columns={"pin id_x": "pin id", "truckParkingSpotCount_x": "truckParkingSpotCount"}, inplace=True)
id_y.rename(columns={"pin id_y": "pin id", "truckParkingSpotCount_y": "truckParkingSpotCount"}, inplace=True)
unique_id = pd.concat([id_x, id_y], ignore_index=True)

In [53]:
unique_id.drop_duplicates(inplace=True)

In [54]:
unique_id

                              pin id  truckParkingSpotCount
0   0f7dfe5e8787efa0406adbb556d76c4a                    0.0
1   116e195af1954fe5253cf0a55f07ef48                    0.0
2   1961aadca386eb5de3a75111cdffcbed                    0.0
3   1b829e73430744463fbf634480db5862                    0.0
4   23363e9a5104d797987048558121b51f                    0.0
..                               ...                    ...
65  e464f78f1b3fa6bfe6d887029bf66f0c                    0.0
66  ebae67e83382b58fedd91e5e1fef26f6                    0.0
67  f36f265c30f00a3c78eb5fba5c89ee87                    0.0
68  fc95b36228f25a538205290b9fc70438                    0.0
69  fd5ac6ce504b74460b93610f39e481f7                   35.0

[70 rows x 2 columns]

In [55]:
#TODO: merge this unique_id with final dataset for truckstopcount update

In [48]:
stop_tab_df.to_excel("Model_Stops.xlsx", index=False)